name: Scrape Indeks & Kurs


# Trigger real-time
on:
  workflow_dispatch:     # Bisa dijalankan manual dari tab Actions
  push:                  # Auto-trigger saat kamu push kode
    branches: [main]     # Sesuaikan dengan branch utama kamu

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r requirements.txt
          playwright install chromium --with-deps
  
- name: Run scraper
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scrap_indeks_kurs.py
