name: Scrape IPOT Market Live

on:
  schedule:
    - cron: '*/15 * * * *'  # Setiap 15 menit
  workflow_dispatch:        # Bisa dijalankan manual juga

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium

    - name: Jalankan scraper
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python scrap_kirim.py
