name: Scrape Indeks & Kurs IPOT

on:
  schedule:
  - cron: '*/1 * * * *'  # tiap menit (hati-hati rate limit)

# atau jika ingin hanya jam kerja (misal Senin-Jumat 08:00–16:00 WIB):
# - cron: '0-9/1 * * * 1-5'  (ini diatur dalam UTC)

jobs:
  scrape-indeks-kurs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Scraper
        run: python scrap_indeks_kurs.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
